apiVersion: apps/v1
kind: Deployment
metadata:
  name: "node-server-deployment"
  labels:
    app: "node-server"
spec:
  selector:
    matchLabels:
      app: "node-server"
  replicas: 10
  template:
    metadata:
      labels:
        app: "node-server"
    spec:
      containers:
        - name: "node-server"
          image: jonasbraga/kubernets-node-server:4.0

          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          volumeMounts:
            - mountPath: "/app/pvc"
              name: node-server-volume

      volumes:
        - name: node-server-volume
          persistentVolumeClaim:
            claimName: node-server-pvc
